### ISSUE TITLE
Selfhosted webhook proxy not working, getting this error in logs

### ISSUE THREAD

**Issue by nolsen42** [LewisTehMinerz/webhook-proxy#2]
2022-06-08T03:50:02.246Z   !!  Failed to submit webhook to self: Error: Parse Error: Content-Length can't be present with Transfer-Encoding
8|webhook-proxy-processor  |     at Socket.socketOnData (node:_http_client:494:22)
8|webhook-proxy-processor  |     at Socket.emit (node:events:527:28)
8|webhook-proxy-processor  |     at addChunk (node:internal/streams/readable:315:12)
8|webhook-proxy-processor  |     at readableAddChunk (node:internal/streams/readable:289:9)
8|webhook-proxy-processor  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
8|webhook-proxy-processor  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
8|webhook-proxy-processor  |   bytesParsed: 1104,
8|webhook-proxy-processor  |   code: 'HPE_UNEXPECTED_CONTENT_LENGTH',
8|webhook-proxy-processor  |   reason: "Content-Length can't be present with Transfer-Encoding",
8|webhook-proxy-processor  |   rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 34 32 39 20 54 6f 6f 20 4d 61 6e 79 20 52 65 71 75 65 73 74 73 0d 0a 58 2d 44 4e 53 2d 50 72 65 66 65 74 63 68 2d 43 6f 6e ... 1300 more bytes>,
8|webhook-proxy-processor  |   config: {
8|webhook-proxy-processor  |     transitional: {
8|webhook-proxy-processor  |       silentJSONParsing: true,
8|webhook-proxy-processor  |       forcedJSONParsing: true,
8|webhook-proxy-processor  |       clarifyTimeoutError: false
8|webhook-proxy-processor  |     },
8|webhook-proxy-processor  |     adapter: [Function: httpAdapter],
8|webhook-proxy-processor  |     transformRequest: [ [Function: transformRequest] ],
8|webhook-proxy-processor  |     transformResponse: [ [Function: transformResponse] ],
8|webhook-proxy-processor  |     timeout: 0,
8|webhook-proxy-processor  |     xsrfCookieName: 'XSRF-TOKEN',
8|webhook-proxy-processor  |     xsrfHeaderName: 'X-XSRF-TOKEN',
8|webhook-proxy-processor  |     maxContentLength: -1,
8|webhook-proxy-processor  |     maxBodyLength: -1,
8|webhook-proxy-processor  |     validateStatus: [Function: validateStatus],
8|webhook-proxy-processor  |     headers: {
8|webhook-proxy-processor  |       Accept: 'application/json, text/plain, */*',
8|webhook-proxy-processor  |       'Content-Type': 'application/json',
8|webhook-proxy-processor  |       'User-Agent': 'WebhookProxy-QueueProcessor/1.0 (https://github.com/LewisTehMinerz/webhook-proxy)',
8|webhook-proxy-processor  |       'Content-Length': 205
8|webhook-proxy-processor  |     },
8|webhook-proxy-processor  |     method: 'post',

**Comment by nolsen42** [comment]
For additional information, I have this proxied through NGINX, with the config provided from devforums

**Comment by LewisTehMinerz** [comment]
Reverse proxy usage should be irrelevant here since the queue processor sends the request directly to the underlying web server rather than going through NGINX.

That's definitely odd and I have also received that error myself. For clarification, does the message actually get sent?

**Comment by LewisTehMinerz** [comment]
bdef050 resolves this.
